# Generated by Django 4.0.5 on 2022-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
